# Google Cloud Load Balancer Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medicine-delivery-ingress
  namespace: medicine-delivery
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "medicine-delivery-ip"
    networking.gke.io/managed-certificates: "medicine-delivery-ssl"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: medicine-delivery.your-domain.com
      http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-cluster-ip
                port:
                  number: 8080
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-cluster-ip
                port:
                  number: 3000
---
# Managed SSL Certificate
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: medicine-delivery-ssl
  namespace: medicine-delivery
spec:
  domains:
    - medicine-delivery.your-domain.com
---
# Static IP Address (create via gcloud command)
# gcloud compute addresses create medicine-delivery-ip --global
