# Order Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: medicine-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: gcr.io/YOUR_PROJECT_ID/order:latest
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: DATABASE_URL
              value: "postgresql://postgres:$(DATABASE_PASSWORD)@postgres-cluster-ip:5432/medicine_delivery"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-password
            - name: RABBITMQ_URL
              value: "amqp://admin:$(RABBITMQ_PASSWORD)@rabbitmq-cluster-ip:5672"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rabbitmq-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-cluster-ip
  namespace: medicine-delivery
spec:
  selector:
    app: order
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP

---
# Delivery Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  namespace: medicine-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: gcr.io/YOUR_PROJECT_ID/delivery:latest
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: DATABASE_URL
              value: "postgresql://postgres:$(DATABASE_PASSWORD)@postgres-cluster-ip:5432/medicine_delivery"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-password
            - name: RABBITMQ_URL
              value: "amqp://admin:$(RABBITMQ_PASSWORD)@rabbitmq-cluster-ip:5672"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rabbitmq-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-cluster-ip
  namespace: medicine-delivery
spec:
  selector:
    app: delivery
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP

---
# Notification Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: medicine-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: gcr.io/YOUR_PROJECT_ID/notification:latest
          ports:
            - containerPort: 3005
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: RABBITMQ_URL
              value: "amqp://admin:$(RABBITMQ_PASSWORD)@rabbitmq-cluster-ip:5672"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rabbitmq-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-cluster-ip
  namespace: medicine-delivery
spec:
  selector:
    app: notification
  ports:
    - port: 3005
      targetPort: 3005
  type: ClusterIP
